# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='released',
            field=models.BooleanField(default=False, verbose_name='aritcle is released'),
        ),
    ]
