# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='is_dir',
            field=models.BooleanField(default=True, verbose_name='File is a directory'),
        ),
    ]
