# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_urlpath_is_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlpath',
            name='is_dir',
        ),
        migrations.RemoveField(
            model_name='urlpath',
            name='released',
        ),
        migrations.AddField(
            model_name='article',
            name='is_dir',
            field=models.BooleanField(default=True, verbose_name='File is a directory'),
        ),
        migrations.AddField(
            model_name='article',
            name='released',
            field=models.BooleanField(default=False, verbose_name='aritcle is released'),
        ),
    ]
