# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20170626_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_dir',
            field=models.BooleanField(default=False, verbose_name='File is a directory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='released',
            field=models.BooleanField(default=True, verbose_name='aritcle is released'),
        ),
    ]
