# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 12:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20170710_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='moved_to',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Article path was moved to this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='wiki.URLPath', verbose_name='Moved to'),
        ),
    ]
