# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_urlpath_moved_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_dir',
        ),
        migrations.RemoveField(
            model_name='article',
            name='released',
        ),
    ]
