# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20170905_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_dir',
            field=models.BooleanField(default=False, verbose_name='File is a directory'),
        ),
        migrations.AddField(
            model_name='article',
            name='released',
            field=models.BooleanField(default=True, verbose_name='aritcle is released'),
        ),
    ]
